#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 30 14:20:32 2021

@author: bryony
"""

file = askopenfile(mode ='r', filetypes =[('Python Files', '*.dot')])
FILE_INPUT = file.name
graph = nx.DiGraph(imagefunc(file.name))  
nx.set_node_attributes(graph, '<&beta;<SUB>456</SUB>>', 'label')
imgrender(graph)
graph.nodes()


