name: Docs

on:
  # on push to any branch
  push:
  # On workflow dispatch events (i.e. can manually run)
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # Docs building is only really worth doing once, with the minimum supported python, although could be included in regular CI for completeness
      matrix:
        os:
          - ubuntu-24.04
        python-version:
          - "3.9"

    steps:
      # Checkout this repository
      - uses: actions/checkout@v4

      # Select the appropriate python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # Install non-python dependencies. This could be skipped if we manually installed docs dependencies
      - name: Install non-python dependencies
        run: |
          sudo apt-get -y install graphviz

      # Install the package into the current python environment with the docs extra group
      - name: Install polychron and docs dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install .[docs]

      # Build the documentation
      - name: Run mkdocs build
        run: |
          python3 -m mkdocs build
